### ISSUE TITLE
[MAJOR] Remove ACE dependence

### ISSUE THREAD

**Issue by abebeos** [abebeos/azerothcore-wotlk#1]
(original issue: #3451) 

# Tasks

## Done
- [x]  Update `acelite`, set lib to `STATIC` and disable incorrect fix `std::auto_ptr` #3450
- [x] Config - #3453
- [x]  Method_Request - #3459
- [x]  `AutoPtr` - #3454
- [x]  `OS_NS_time` - #3455
- [x]  `Atomic_Op` - [4a9476b](https://github.com/azerothcore/azerothcore-wotlk/commit4a9476bbfd2f8c960a0507e7a733a1f2cae8163a)
- [x]  `Basic_Types` - #3745

## Low Difficulty

(process this list, move to mid difficulty once stuck)

- [ ]  `Stack_Trace`
- [ ]  `Task`
- [ ]  `Guard_T`
- [ ]  `Event`
- [ ]  `Based`
- [ ]  `TSS_T`
- [ ]  `INET_Addr`
- [ ]  `Reactor`
- [ ]  `Acceptor`
- [ ]  `Future`
- [ ]  `Queue`
- [ ]  `Semaphore`
- [ ]  Configuration

## Separate Issues

- [ ] #99 - Thread 
 
## WIP

* #3815
